event/urls.py
from django.conf.urls import url
from .views import *

app_name = "event"

urlpatterns = [

    url(r'^$', home_view, name='home'),

    # /events/
    url(r'^events/$', event_index, name='index'),

    # /myevents/
    url(r'^myevents/$', event_index_user, name='user_index'),

    # /notifications/
    url(r'^notifications/$', list_notifications, name='notification'),

    # /event/create/
    url(r'^event/create/$', event_create, name='add'),

    # /event/slug/
    url(r'^event/(?P<slug>[\w-]+)/$', event_detail, name='detail'),

    # /event/slug/edit/
    url(r'^event/(?P<slug>[\w-]+)/edit/$', event_update, name='edit'),

    # /event/slug/delete/
    url(r'^event/(?P<slug>[\w-]+)/delete/$', event_delete, name='delete'),

    # /event/slug/register
    url(r'^event/(?P<slug>[\w-]+)/register/$', event_register, name='register'),
]

eventhub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('event.urls')),

    url(r'^accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from .choices import STATUSES, EVENT_TOPICS, EVENT_TYPES


def upload_location(instance, filename):
    return "event/{}/{}".format(instance.slug, filename)


class EventManager(models.Manager):
    def active(self):
        return self.filter(status='live').filter(end__gte=timezone.now())

    def draft(self):
        return self.filter(status='draft')

    def past(self):
        return self.filter(end__lte=timezone.now())


class Event(models.Model):

    organizer = models.ForeignKey('accounts.User', related_name='organizer_events')
    attendees = models.ManyToManyField('accounts.User', blank=True, related_name='registered_events')

    title = models.CharField(max_length=255, verbose_name="Event Title")
    location = models.CharField(max_length=200)
    online = models.BooleanField(default=False)
    start = models.DateTimeField()
    end = models.DateTimeField()
    description = RichTextField(null=True, blank=True)
    image = models.FileField(upload_to=upload_location, null=True, blank=True)
    capacity = models.IntegerField()
    organizer_name = models.CharField(max_length=250)

    event_type = models.CharField(max_length=200, choices=EVENT_TYPES, blank=True)
    event_topic = models.CharField(max_length=200, choices=EVENT_TOPICS, blank=True)

    status = models.CharField(max_length=10, choices=STATUSES)
    slug = models.SlugField(unique=True)

    objects = EventManager()

    def get_absolute_url(self):
        return reverse('event:detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ["end"]

    def __str__(self):
        return self.title + " - " + self.organizer_name


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug

    qs = Event.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "{}-{}".format(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *arg, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Event)


# class TicketType(models.Model):
#     eb_id = models.CharField(max_length=255, unique=True, verbose_name='Eventbrite ID')
#     name = models.CharField(max_length=255)
#     description = models.TextField(null=True)
#     cost = MoneyField(max_digits=10, decimal_places=2, default_currency=DEFAULT_CURRENCY)
#     fee = MoneyField(max_digits=10, decimal_places=2, default_currency=DEFAULT_CURRENCY)
#     donation = models.BooleanField(default=False)
#     free = models.BooleanField(default=False)
#     event = models.ForeignKey('Event', related_name='tickets')
#     quantity_sold = models.IntegerField()
#
#     def __str__(self):
#         return self.name

event/forms.py
from django import forms
from .models import Event
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field, MultiField, Div
from ckeditor.widgets import CKEditorWidget


class EventCreateForm(forms.ModelForm):
    start = forms.DateTimeField(widget=forms.TimeInput(format='%Y-%m-%d %H:%M'), label="Starts")
    end = forms.DateTimeField(widget=forms.TimeInput(format='%Y-%m-%d %H:%M'), label="Ends")
    image = forms.FileField(label='Event Image', required=False)
    description = forms.CharField(widget=CKEditorWidget(), label='Event Description', required=False)
    online = forms.BooleanField(label='Online Event')

    def __init__(self, *args, **kwargs):
        super(EventCreateForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                "Event Details",
                'title',
                'location',
                'online',
                Div(
                    Div('start', css_class='col-md-6', ),
                    Div('end', css_class='col-md-6', ),
                    css_class='row',

                ),
                'image',
                'description',
                'organizer_name',
            ),
            Fieldset(
                "Create Tickets",
                'capacity',
            ),
            Fieldset(
                "Additional Settings",
                'event_type',
                'event_topic',
            ),
            # ButtonHolder(
            #     Submit('submit', 'Submit', css_class='btn btn-primary')
            # )
        )

    class Meta:

        model = Event
        fields = [
            'title',
            'location',
            'online',
            'start',
            'end',
            'image',
            'organizer_name',
            'description',
            'event_type',
            'event_topic',
            'capacity',
        ]


class EventRegisterForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)

    def __init__(self, *args, **kwargs):
        super(EventRegisterForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                "Attendee Information",
                'first_name',
                'last_name',
            ),
            Fieldset(
                "Permission",
                'email',
            ),
            # ButtonHolder(
            #     Submit('submit', 'Submit', css_class='btn btn-primary')
            # )
        )

event/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect, Http404
from django.contrib.auth.decorators import login_required
from .forms import EventCreateForm, EventRegisterForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from .models import Event
from django.contrib import messages
from datetime import datetime, timedelta
from django.conf import settings
from notification.models import Notification


def home_view(request):
    return render(request, "home.html")


def event_index(request):
    event_list = Event.objects.active()
    events = pagination(request, event_list)
    return render(request, "event/index.html", {"events": events})


def event_index_user(request):
    events = Event.objects.filter(organizer=request.user)
    return render(request, "event/index.html", {"events": events})


def event_detail(request, slug):
    event = get_object_or_404(Event, slug=slug)

    notify = request.GET.get('notify')
    if notify and request.user == event.organizer:
        notification = Notification.objects.get(id=notify)
        notification.read = True
        notification.save()

    return render(request, "event/detail.html", {'event': event})


def event_create(request):
    organizer_name = request.user.get_full_name()
    start = (datetime.today() + timedelta(days=7)).replace(hour=13, minute=0)
    end = start + timedelta(hours=3)

    form = EventCreateForm(request.POST or None, request.FILES or None,
                           initial={
                                'organizer_name': organizer_name,
                                'start': start,
                                'end': end
                           })
    if form.is_valid():
        event = form.save(commit=False)
        event.organizer = request.user
        if 'draft' in request.POST:
            event.status = "draft"
        else:
            event.status = "live"
        event.save()
        messages.success(request, "Event successfully created.")

        return HttpResponseRedirect(event.get_absolute_url())

    context = {
        'form': form,
        'title': 'Create An Event',
        'primary': 'Create Event',
    }
    return render(request, 'event/event_create.html', context)


def event_update(request, slug):
    event = get_object_or_404(Event, slug=slug)

    if event.status == 'draft':
        primary = 'Make Live'
    else:
        primary = 'Update Event'

    if request.user != event.organizer:
        raise Http404

    form = EventCreateForm(request.POST or None, request.FILES or None, instance=event)
    if form.is_valid():
        event = form.save(commit=False)
        if 'draft' in request.POST:
            event.status = "draft"
        elif 'live' in request.POST:
            event.status = "live"
        else:
            return HttpResponseRedirect(event.get_absolute_url())
        event.save()

        messages.success(request, "Changes has been saved.")
        return HttpResponseRedirect(event.get_absolute_url())

    context = {
        'form': form,
        'title': 'Edit Event',
        'primary': primary,
        'status': event.status,
    }
    return render(request, "event/event_create.html", context)


def event_delete(request, slug):
    event = get_object_or_404(Event, slug=slug)
    event.delete()
    return redirect("event:user_index")


def event_register(request, slug):
    if not request.user.is_authenticated:
        return redirect('{}?next={}'.format(settings.LOGIN_URL, request.path))

    attendee_name = request.user.first_name
    attendee_surname = request.user.last_name
    attendee_email = request.user.email

    form = EventRegisterForm(request.POST or None, request.FILES or None,
                                initial={
                                    'first_name': attendee_name,
                                    'last_name': attendee_surname,
                                    'email': attendee_email,
                                })
    if form.is_valid():
        # name = form.cleaned_data.get('first_name')
        # surname = form.cleaned_data.get('last_name')
        # email = form.cleaned_data.get('email')
        event = get_object_or_404(Event, slug=slug)
        request.user.registered_events.add(event)
        Notification.send(actor=event, receiver=event.organizer, message='Your event has a new attendee.')
        messages.success(request, "You have successfuly registered the event.")
        return HttpResponseRedirect(event.get_absolute_url())
    return render(request, "crispy/form.html", {"form": form, "title": "Register Event"})


def list_notifications(request):
    notifys = request.user.notifications.unread()
    return render(request, 'notifications/index.html', {'notifications': notifys})


def pagination(request, obj_list):
    query = request.GET.get('q')
    if query:
        if query.strip():
            obj_list = obj_list.filter(
                Q(title__icontains=query)
            ).distinct()

    paginator = Paginator(obj_list, 5)  # Show 5 posts per page

    page = request.GET.get('page')
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    return objects

templates/event/detail.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="row">

                {% include 'messages/success.html' %}

                <div class="thumbnail">
                    {% if event.image %}
                        <img src="{{ event.image.url }}" class="img-responsive">
                    {% endif %}
                    <div class="caption">
                        <h1>
                            {{ event.title }}
                            {% if event.status == 'draft' %} <span style="color: #bf0000;">Draft</span> {% endif %}
                        </h1>
                        <p><span style="color: #2b669a">Organizer: <strong>{{ event.organizer_name }}</strong></span></p>
                        <hr>
                        <p>{{ event.description|safe|linebreaks }}</p>

                        <br><br><hr>
                        <p>
                            {% if event.attendees.all %}
                                <strong>Attendees: </strong>
                                {% for attendee in event.attendees.all %}
                                    {{ attendee.get_full_name }},
                                {% endfor %}
                            {% endif %}
                        </p>
                        <p>
                            {% if event.status == 'live' %}
                                <a href="{% url 'event:register' event.slug %}" class="btn btn-primary btn-sm" role="button">Register</a>
                            {% endif %}
                            {% if user == event.organizer %}
                                <a href="{% url 'event:edit' event.slug %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                                <a href="{% url 'event:delete' event.slug %}" class="btn btn-primary btn-sm" role="button">Delete</a>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/event/event_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block body %}

    {% include 'messages/success.html' %}

    <div class="container">
        <div class="col-sm-7 col-sm-offset-2">
            <h1>{{ title }}</h1>
            <hr>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% crispy form %}
                {{ form.media }}
                <div>
                    {% if status != 'live' %}
                        <input class="btn btn-primary" type="submit" name="live" value="{{ primary }}">
                        <input class="btn btn-default" type="submit" name="draft" value="Save">
                    {% else %}
                        <input class="btn btn-primary" type="submit" name="live" value="Save">
                        <input class="btn btn-default" type="submit" name="cancel" value="Cancel">
                    {% endif %}
                </div>
                <br><br>
            </form>
        </div>
    </div>

{% endblock %}

templates/event/index.html
{% extends 'base.html' %}

{% block body %}
    {% if events %}
        <div class="container">
            <div class="col-sm-6 col-sm-offset-3">
                {% for event in events %}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="thumbnail">
                                {% if event.image %}
                                   <a href="{% url 'event:detail' event.slug %}"><img src="{{ event.image.url }}" class="img-responsive"></a>
                                {% endif %}
                                <div class="caption">
                                    <h2>
                                        <a href="{% url 'event:detail' event.slug %}">{{ event.title }}</a>
                                        {% if event.status == 'draft' %} <span style="color: #bf0000;"> | Draft</span> {% endif %}
                                    </h2>
                                    <p><span style="color: #2b669a">Organizer: <strong>{{ event.organizer_name }}</strong></span></p>
                                    <hr>
                                    <p>{{ event.description|safe|linebreaks|truncatewords:50 }}</p>
                                    <p>
                                        <a href="{% url 'event:detail' event.slug %}" class="btn btn-primary btn-sm" role="button">View</a>
                                        {% if event.status == 'live' %}
                                            <a href="{% url 'event:register' event.slug %}" class="btn btn-primary btn-sm" role="button">Register</a>
                                        {% endif %}
                                        {% if user == event.organizer %}
                                            <a href="{% url 'event:edit' event.slug %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                                            <a href="{% url 'event:delete' event.slug %}" class="btn btn-primary btn-sm" role="button">Delete</a>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div style="text-align: center;">
                    {% include 'event/pagination.html' %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="container">
            <h2>There is no event.</h2>
        </div>
    {% endif %}

{% endblock %}

templates/event/pagination.html
<div class="pagination">
    <span class="pager">
        {% if events.has_previous %}
            <li><a href="?page={{ events.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a></li>
        {% endif %}

        <span style="color: #2b669a;">
            <strong>Page {{ events.number }} of {{ events.paginator.num_pages }}</strong>
        </span>

        {% if events.has_next %}
            <li><a href="?page={{ events.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a></li>
        {% endif %}
    </span>

</div>